language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.2
before_install:
  - sudo apt-get update
  - sudo apt-get upgrade
  - sudo apt-get install sqlite3-dev libsqlite3-dev
  - sudo apt-get -y purge sqlite3 sqlite3-dev
  - gem update bundler
script: ./script/travis_build.sh
branches:
  only:
    - master
    - production
