language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.2
before_install:
  - sudo apt-get install sqlite3 libsqlite3-dev
  - sudo apt-get -y purge sqlite3 sqlite3-dev
  - gem update bundler
script:
  - mysql -e 'create database ferry_test;'
  - psql -c 'create database ferry_test;' -U postgres
  - bundle exec rspec
branches:
  only:
    - master
    - production
