language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.2
before_install:
  - gem update bundler
script:
  - mysql -e 'create database ferry_test;'
  - psql -c 'create database ferry_test;'
  - bundle exec rspec
branches:
  only:
    - master
    - production
